### PR TITLE
Add `text.md` scope

### PR DESCRIPTION
**Pull request by SpainTrain**
[Review on Reviewable](https://reviewable.io/reviews/atomlinter/linter-markdown/12)

### CODE REVIEW

**Comment by SpainTrain** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/atomlinter/linter-markdown/12)*

**Comment by steelbrain** [comment]
@SpainTrain Any ideas which language uses this scope?

**Comment by SpainTrain** [comment]
On grammar picker its "Markdown"

https://github.com/burodepeper/language-markdown/blob/master/grammars/language-markdown.json

**Comment by SpainTrain** [comment]
In my atom setup, this repo's changelog file is auto detected as this.

**Comment by steelbrain** [comment]
LGTM!

**Pull request merged**
