### PR TITLE
Automatically install linter

### LINKED ISSUE #6: Install `linter` automatically.
By using [`atom-package-deps`](https://github.com/steelbrain/package-deps) you are able to install `linter` automatically on activation. This will allow new Atom users to install only your package and nothing else, removing one step from the installation process.

Please see AtomLinter/linter-ruby#38 for example.

### PR DESCRIPTION
**Pull request by Arcanemagus**
Automatically install the linter package if it isn't already installed.

Fixes #6.

[Review on Reviewable](https://reviewable.io/reviews/atomlinter/linter-markdown/26)

### CODE REVIEW

**Comment by Arcanemagus** [comment]
@wooorm since I love your beautiful documentation, can you make sure what I did there is sufficient?

**Comment by Arcanemagus** [comment]
Did a bit more looking into it, leaving out the `@return` should be fine since the function returns undefined. Merging.

**Comment by wooorm** [comment]
Great! I'm personally in favour of the newlines after block-comments, but can adjust to the project style guide :)

**Comment by Arcanemagus** [comment]
Actually there isn't one, just all but the two I removed had no line break so I made things consistent :wink:

(Personally I prefer none anyway, but it's not a big deal either way)

**Comment by Arcanemagus** [comment]
@wooorm looks like a release hasn't been pushed out in a while, do you want to push one up or should I?

**Comment by wooorm** [comment]
AWFK, could you?

**Comment by Arcanemagus** [comment]
Sure

**Comment by Arcanemagus** [comment]
v1.3.0 released :wink:.

**Comment by wooorm** [comment]
:+1:

**Comment by Arcanemagus** [comment]
Wow, I completely failed to actually list `linter` as a dependency here, causing #112. 😞

**Pull request merged**
