### PR TITLE
Add specs

### LINKED ISSUE #13: Add specs
Add at min some sanity check specs.

### PR DESCRIPTION
**Pull request by Arcanemagus**
Add some basic tests for functionality.

Fixes #13.

[Review on Reviewable](https://reviewable.io/reviews/atomlinter/linter-markdown/24)

### CODE REVIEW

**Comment by Arcanemagus** [comment]
One thing to note about this, `npm test` is gone, since any meaningful testing would need `atom`/`apm` anyway. As long as that is fine with you merge away :wink:.

**Comment by Arcanemagus** [comment]
Adding it back is a small PR away if this is an issue, merged in.

**Comment by wooorm** [comment]
So now I just run 'apm test', if I'm correct?

Good work 👍

**Comment by Arcanemagus** [comment]
Yep, `apm test` will test the functionality of the plugin itself. (`npm run lint` is unchanged).

**Pull request merged**
