### PR TITLE
add info on how to use a specific config

### PR DESCRIPTION
**Pull request by oupala**
add information about how to install and use this package in different configurations

### CODE REVIEW

**Comment by oupala** [comment]
Is there a reason for not merging this pull request?

**Comment by wooorm** [comment]
@Arcanemagus could you see what’s up with circleci? I don’t have admin access anymore.

**Comment by Arcanemagus** [comment]
It looks like when this PR was created they had based it on a commit from before the CircleCI 2.0 configuration was added.

@oupala are you still interested in updating this PR? If so it will need to be rebased on `master` (and there are several changes I would say it needs, but I'm not going to do a full review if it's not going to be worked on).

**Comment by oupala** [comment]
This PR contains only documentation changes. Do you really think a rebase is mandatory?

Is a rebase possible with GitHub? I'm asking as my origin repo has been deleted since the time the PR is waiting.

**Comment by Arcanemagus** [comment]
> This PR contains only documentation changes. Do you really think a rebase is mandatory?
> Is a rebase possible with GitHub?

I _could_ bypass the protections in place and merge this, but that's reserved for when there is no other way, which isn't the case here.

> I'm asking as my origin repo has been deleted since the time the PR is waiting.

That.... definitely poses some issues. If you want to create a fork again you could cherry-pick the commit from here and start a new PR where you can make changes.

**Comment by oupala** [comment]
I had to create a new pull request #211.

Feel free to merge it now!

**Pull request closed without merging**
