### PR TITLE
Switch to js

### PR DESCRIPTION
**Pull request by wooorm**
I succesfully tested this, but suggest someone also tries it before merging.

Also: I’m probably not as experienced with linter as you all, so let me know if I missed something.

Should be merged after GH-20.

[Review on Reviewable](https://reviewable.io/reviews/atomlinter/linter-markdown/21)

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Might want to rebase this on master now that #20 has been merged in?

Also this might be a good opportunity to add some specs so the linter itself is being tested in all the different build environments.

**Comment by Arcanemagus** [comment]
Also if you keep `index.js` in the `lib` folder the build scripts will [automatically](https://github.com/atom/ci/blob/master/build-package.sh#L76) run any configured linters on it.

**Comment by wooorm** [comment]
OK, I’ll amend, update `index.js`, and merge.

Regarding the tests: definitely, I already checked out tests in [linter-eslint](https://github.com/AtomLinter/linter-eslint/tree/master/spec), but was planing on doing that in another PR. Also: I’m not very familiar with the atom(-linter) interface, so maybe someone else?

**Comment by Arcanemagus** [comment]
I'll see if I have time later today. If you want another example the last one I added specs to is [linter-bootlint](https://github.com/AtomLinter/linter-bootlint/tree/v1.0.0/spec), so that's what I would be basing things off of :wink:.

**Comment by wooorm** [comment]
I’ve updated per your suggestions, could you `apm link`, and test, and publish?

**Comment by wooorm** [comment]
:+1:

**Pull request merged**
